### PR TITLE
Updates for Safari Compatability

### PR DESCRIPTION
**Pull request by deeheber**
Replaced "document.getElementById" with "document.querySelector" in activities.js and now the js appears to work properly on the activities.html page for Safari, Chrome, and Firefox (don't have IE).

If you could please download the files and test this on your end too before merging this into the master...that would be great. Thanks!

### CODE REVIEW

**Comment by risachi** [comment]
I'm at work now so decided to test this in IE ... there's a bunch of wacky problems, mostly elements of the pages not displaying properly or have completely moved somewhere else. The js for the activities.html page doesn't work at all.

Not sure if we want to tackle this though, since it looks like it'd be a big project just to get the site working in IE. (For the record, I'm on Windows 7 Enterprise; not sure which version of IE.)

**Comment by deeheber** [comment]
Oh snap. Yeah I figured IE probably wouldn't want to play nice. Thanks for testing that! Unless anyone else objects, I'm ok with just having it work on Chrome/Firefox/Safari for the purposes of this project.

Thoughts @jacobshillman @Randallonius @risachi ?

Otherwise, feel free to make changes on this branch or create a new branch, I'm thinking it's the selectors on lines 26, 32, 37, and 42 in activities.js on this branch that is somehow not recognized by IE. We’d have to find a dom selector method that’s accepted by all four major browsers or use a third party JS library like jQuery.

**Comment by risachi** [comment]
I'm 100% ok with not making it work in IE. It would be a big headache, and the preso is tomolo... Unless one of us has TONS of free time and gusto, I guess. :stuck_out_tongue:

**Comment by Randallonius** [comment]
I'm totally cool with that. Internet Explorer can die a fiery death.

**Comment by risachi** [comment]
I tested this in Safari. TLDR; it's wonky. Nevermind the display issues (nav bar on right, header and nav bar text aren't in alignment anymore). As for the activities.html page, It appears to be functional, however the results list is displayed below the Reset button - so I almost didn't even notice it.

**Pull request merged**
